DjangoProject/djangotestproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('testsite.urls')),
    path("users/", include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),

]

handler403 = 'testsite.views.permission_denied'
handler404 = 'testsite.views.page_not_found'
handler500 = 'testsite.views.server_error'

DjangoProject/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

DjangoProject/users/models.py
from django.db import models

# Create your models here.

DjangoProject/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="login", widget=forms.TextInput())
    password = forms.CharField(label="password", widget=forms.PasswordInput())


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Login")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'First Name',
            'last_name': 'Last name'
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('passwords do not match')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('this email already exists')
        return email

DjangoProject/users/views.py
from symtable import Class

from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from .forms import LoginUserForm, RegisterUserForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Authorization'}


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

DjangoProject/users/templates/users/login.html
{% extends 'base.html' %}

{% block body %}

<form method="post" class="login-form">
  <h1>Authorization</h1>
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />
  {{ form.as_p }}
  <p><button type="submit">Login</button></p>
  <p><a href="{% url 'users:password_reset' %}">forgot your password?</a></p>
</form>

{% endblock %}

DjangoProject/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block body %}
<form class="login-form" style="text-align: center;">
  <h1>Password Reset Complete</h1>
  <p>Your password has been successfully changed.</p>
  <p>
    <a href="{% url 'users:login' %}" style="color: #00bfff; text-decoration: none;">
      Click here to log in
    </a>
  </p>
</form>
{% endblock %}

DjangoProject/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block body %}
<form method="post" class="login-form">
  <h1>Set New Password</h1>
  {% csrf_token %}
  {% if form.errors %}
  <div style="color:red;">
    {{ form.errors }}
  </div>
{% endif %}

  {% if form.errors %}
    <p style="color: #d9534f; text-align: center; margin-bottom: 20px;">
      Please correct the errors below.
    </p>
  {% endif %}

  {{ form.as_p }}

  <p><button type="submit">Change Password</button></p>

  <p style="text-align: center;">
    <a href="{% url 'users:login' %}" style="color: #00bfff; text-decoration: none;">Back to Login</a>
  </p>
</form>
{% endblock %}

DjangoProject/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<h1>Reset password</h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

DjangoProject/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

DjangoProject/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block body %}
<form method="post" class="login-form">
  <h1>Reset Password</h1>
  {% csrf_token %}

  {% if form.errors %}
    <p style="color: #d9534f; text-align: center; margin-bottom: 20px;">
      Please correct the errors below.
    </p>
  {% endif %}

  <div class="form-group">
    {{ form.email.label_tag }}
    {{ form.email }}
    {% if form.email.errors %}
      <div class="field-error" style="color: #d9534f;">{{ form.email.errors }}</div>
    {% endif %}
  </div>

  <p><button type="submit">Send Reset Link</button></p>

  <p style="text-align: center;">
    <a href="{% url 'users:login' %}" style="color: #00bfff; text-decoration: none;">Back to Login</a>
  </p>
</form>
{% endblock %}

DjangoProject/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block body %}
<div class="content">
  <h2 class="transaction-title" style="text-align: center;">Register</h2>

  <form method="post" class="login-form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />

    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
          <div style="color: red;">{{ field.errors|striptags }}</div>
        {% endif %}
      </div>
    {% endfor %}

    <button type="submit" class="btn">Register</button>
  </form>
</div>
{% endblock %}

DjangoProject/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block body %}
<h1> Welcome </h1>

<p>You have successfully registered, to enter please log in
    <a href="{% url 'users:login' %}">Login</a>
</p>
{% endblock %}