DjangoProject/djangotestproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('testsite.urls')),
    path("users/", include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),

]

handler403 = 'testsite.views.permission_denied'
handler404 = 'testsite.views.page_not_found'
handler500 = 'testsite.views.server_error'

DjangoProject/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

DjangoProject/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" href="{% static 'testsite/css/styles.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="navbar">
        <div class="left-links">
            <a href="{% url 'transaction' %}">Transaction</a>
            <a href="{% url 'category' %}">Categories</a>
            <a href="{% url 'statistic' %}">Statistic</a>
            <a href="{% url 'about' %}">About</a>
        </div>

    <div class="right-links">
        {% if user.is_authenticated %}
            <span class="username"><i class="fas fa-user"></i> {{ user.username }}</span>
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">
                    <i class="fas fa-sign-out-alt" style="margin-right: 5px;"></i> Logout
                </button>
            </form>
        {% else %}
            <a href="{% url 'users:login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
            <a href="{% url 'users:register' %}"><i class="fas fa-user-plus"></i> Register</a>
        {% endif %}
    </div>

    </div>

    <div class="main-container">
        <div class="sidebar">
            <ul>
                <li><a href="{% url 'transaction-add' %}">Add new transaction</a></li>
                <li><a href="{% url 'category-add' %}">Add new category</a></li>
                <li><a href="{% url 'exchange' %}">Current value</a></li>
            </ul>
        </div>

        <div class="content">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>